### PR TITLE
Getting the extension to inject js scripts

### PR DESCRIPTION
**Pull request by Guy-Adler**
Currently, it just injects AP++ on `document_end` (the FMC code is there, but I'm not adding it yet).
- The file `geofs_types.d.ts` MUST end in `.d.ts` because it only contains the type definitions, not the actual code.
- `geofs_types.js` needs to be deleted.
- `@types/jquery` needs to be installed.

### CODE REVIEW

**Comment by Guy-Adler** [comment]
I think the duplicate function implementation error is caused by the fact that ts sees the files in `extension` and in `build\extension` as in the same project, and the same function is defined in both files. might need to change the `tsconfig.json` to ignore `build\extension`

**Comment by nicolas377** [comment]
tsconfig.json shouldn't ignore build/extension, since that will break the build function

**Comment by nicolas377** [comment]
you just need to export a empty object, since they won't rely on each other cross-file

**Comment by Guy-Adler** [comment]
Do you want me to throw in spoilers arming before merging?

**Comment by nicolas377** [comment]
I think we're good for now. Beta 3 will just be ap++ and fmc

**Review by nicolas377 — APPROVED** [review]
looks great! i'll merge this

**Pull request merged**
